### ISSUE TITLE
Cannot translate from Spanish?

### ISSUE THREAD

**Issue by andytheengineerguy** [DeskTranslate/DeskTranslate-Mac#4]
Firstly, thank you so much for making this available for download, this is an awesome idea and I love the story and motivations behind building this!

One thing though, the list of languages to translate _from_ feels incomplete. For example, Spanish is not available (which was the reason I downloaded this in the first place).

Diving into the code I noticed that the fromLanguage.csv also does not contain Spanish

<img width="426" alt="image" src="https://github.com/DeskTranslate/DeskTranslate-Mac/assets/26783020/2bf8122d-3771-4556-82f2-128ec7a0bfca">

Are there plans to support this? If I had some instruction, I'd be happy to add/test this myself and then push up these changes. Lemme know :)

**Comment by hua-lun** [comment]
> Firstly, thank you so much for making this available for download, this is an awesome idea and I love the story and motivations behind building this!
> 
> One thing though, the list of languages to translate _from_ feels incomplete. For example, Spanish is not available (which was the reason I downloaded this in the first place).
> 
> Diving into the code I noticed that the fromLanguage.csv also does not contain Spanish
> 
> <img alt="image" width="426" src="https://private-user-images.githubusercontent.com/26783020/257955798-2bf8122d-3771-4556-82f2-128ec7a0bfca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTg4NjMsIm5iZiI6MTcwOTcxODU2MywicGF0aCI6Ii8yNjc4MzAyMC8yNTc5NTU3OTgtMmJmODEyMmQtMzc3MS00NTU2LTgyZjItMTI4ZWM3YTBiZmNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA5NDkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmMDYwNDQzOGFkNDkyOTFhNzc4OTJmMTlkNzdlMTNkMzJmYWNmNDQ2Yjg1ZDZkNTEyMTdiOWUwYWQ3Y2E4OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8S_bRuIuzyEEZ7iX48rHdbUX1wPpDvWVN045xNe_SAY">
> Are there plans to support this? If I had some instruction, I'd be happy to add/test this myself and then push up these changes. Lemme know :)

Hi @andytheengineerguy 

Thank you for the support!
In the latest update, we have added Spanish into the list of supported languages to translate from.
